sound_board/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from sound import views
from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.MainView.as_view(), name='main'),
    path('new/', views.CreatePost.as_view(), name='new'),
    path('signup/', user_views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.ProfileView.as_view(), name='profile'),
    path('soundboard/', views.SoundBoard.as_view(), name='userboard'),
    path('leaderboard/', views.LeaderBoard.as_view(), name = 'leaderboard'),
]
handler404 = views.handler404
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sound/models.py
from django.db import models
from PIL import Image
from django.contrib.auth.models import User


# Create your models here.
class SoundPost(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, default='')
    sound = models.FileField(upload_to='sounds')
    image = models.ImageField(upload_to='images', default='images/default.png')
    title = models.CharField(max_length=20)
    adds = models.IntegerField(default=0)

    def save(self, **kwargs):
        super().save()
        img = Image.open(self.image.path)

        if img.height > 100 or img.width > 100:
            img.thumbnail((100, 100))
            img.save(self.image.path)

    def __str__(self):
        return self.title


class UserSoundBoard(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    sounds = models.ForeignKey(SoundPost, on_delete=models.CASCADE)

    def __str__(self):
        return 'User = ' + str(self.user) + ' | ' + 'Sound = ' + str(self.sounds)

users/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    adds = models.IntegerField(default=0)

    def __str__(self):
        return str(self.user)

sound/forms.py
from django import forms
from .models import SoundPost


class ButtonForm(forms.Form):
    val = forms.CharField()


class DeleteButton(forms.Form):
    prim_key = forms.CharField()


class SearchBar(forms.Form):
    search = forms.CharField(max_length=23)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    full_name = forms.CharField(max_length=30, required=False, help_text='Optional')
    email = forms.EmailField(max_length=256, required=True)

    class Meta:
        model = User
        fields = ('username', 'full_name', 'email', 'password1', 'password2',)


class DeletePost(forms.Form):
    prim_key = forms.CharField()

sound/views.py
from django.views.generic import ListView, CreateView
from django.views import View
from .models import SoundPost, UserSoundBoard
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, HttpResponseRedirect
from .forms import ButtonForm, DeleteButton, SearchBar
from django.core.paginator import Paginator
from users.models import Profile

'''class MainView(ListView):
    template_name = 'sound/main.html'
    context_object_name = 'sound'
    model = UserSoundBoard

    def get_queryset(self):
        return SoundPost.objects.all().order_by('?')

    @staticmethod
    def post(request):
        form = ButtonForm(request.POST)
        if form.is_valid():
            pk_key = form.cleaned_data['val']
            post = SoundPost.objects.filter(pk=pk_key).first()
            model = UserSoundBoard(user=request.user, sounds=post)
            model.save()
        return HttpResponseRedirect('/')
'''


class MainView(ListView):
    paginate_by = 16
    model = SoundPost
    context_object_name = 'sound'
    template_name = 'sound/main.html'

    @staticmethod
    def post(request):
        form = ButtonForm(request.POST)
        search_qr = SearchBar(request.POST)

        if search_qr.is_valid():
            user_qr = search_qr.cleaned_data['search']
            results = SoundPost.objects.filter(title__icontains=user_qr)
            context = {
                'sound': results,
                'search': search_qr,
            }
        else:
            context = {
                'sound': SoundPost.objects.all().order_by('?'),
                'search': search_qr,
            }

        if form.is_valid():
            pk_key = form.cleaned_data['val']
            post = SoundPost.objects.filter(pk=pk_key).first()
            if len(str(UserSoundBoard.objects.filter(user=request.user)).split(',')) == 16:
                HttpResponseRedirect('/')
            else:
                a = Profile.objects.filter(user=post.author).first()
                a.adds += 1
                a.save()
                post.adds += 1
                post.save()
                model = UserSoundBoard(user=request.user, sounds=post)
                model.save()

        return render(request, 'sound/main.html', context)


class CreatePost(LoginRequiredMixin, CreateView):
    model = SoundPost
    success_url = '/'
    fields = ['title', 'sound', 'image']
    template_name = 'sound/postsound.html'

    def form_valid(self, form):
        audio = str(form.cleaned_data['sound'])
        audio_type = audio.split('.')[-1:][0]
        if 'mp3' not in audio_type:
            return HttpResponseRedirect('/new/')
        else:
            form.instance.author = self.request.user
            return super().form_valid(form)


class SoundBoard(LoginRequiredMixin, View):
    @staticmethod
    def get(request):
        user_sounds = UserSoundBoard.objects.filter(user=request.user)
        if not user_sounds.first():
            context = {
                'add_sounds': 'True',
            }
        else:
            context = {
                'user_sound': user_sounds,
            }

        return render(request, 'sound/sound_board.html', context)

    @staticmethod
    def post(request):
        form = DeleteButton(request.POST)
        if form.is_valid():
            prim_key = form.cleaned_data['prim_key']
            if UserSoundBoard.objects.filter(pk=prim_key).first():
                UserSoundBoard.objects.filter(pk=prim_key).first().delete()
        return HttpResponseRedirect('/soundboard/')


'''class LeaderBoard(View):

    @staticmethod
    def get(request):

        context = {
            'profile' :Profile.objects.order_by('-adds')
        }

        return render(request, 'sound/leaderboard.html', context)'''


class LeaderBoard(ListView):
    model = Profile
    context_object_name = 'profile'
    template_name = 'sound/leaderboard.html'
    paginate_by = 100

    def get_queryset(self):
        return Profile.objects.order_by('-adds')


def handler404(request, *args, **kwargs):
    return render(request, 'error_pages/404.html', status=404)

users/views.py
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect,HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.views import generic
from .forms import SignUpForm , DeletePost
from sound.models import SoundPost
from .models import Profile

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            form = SignUpForm(request.POST)

            if form.is_valid():
                form.save()
                username = form.cleaned_data.get('username')
                raw_password = form.cleaned_data.get('password1')
                user = authenticate(username=username, password=raw_password)
                messages.success(request, f'Thanks for making an account {username}!')
                login(request, user)
                Profile.objects.create(user=request.user)
                return redirect('main')

    else:
        form = SignUpForm()

    return render(request, 'users/signup.html', {'form': form})


class ProfileView(generic.View):

    @staticmethod
    def get(request):
        context = {
            'profile': Profile.objects.filter(user = request.user).first(),
            'post': SoundPost.objects.filter(author=request.user),
        }
        template_name = 'users/profile.html'
        return render(request,'users/profile.html',context)


    @staticmethod
    def post(request):
        form = DeletePost(request.POST)

        if form.is_valid():
            data = form.cleaned_data['prim_key']
            SoundPost.objects.filter(pk=data).delete()
        return HttpResponseRedirect('/profile/')

templates/sound/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

     <title>Sound Board</title>
</head>
<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark ">
    <a href="{% url 'main' %}" class="navbar-brand">
        Sound Board
    </a>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav">
            <a class="nav-item nav-link" href="{% url 'main' %}">Home</a>
            {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'userboard' %}">My soundboard</a>
                <a class="nav-item nav-link" href="{% url 'new' %}">New Sound</a>
                <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                <a class="nav-item nav-link" href="{% url 'leaderboard' %}"> LeaderBoard</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}"> Logout</a>
            {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'signup' %}">Register</a>
            {% endif %}
        </div>
        <div class="navbar-nav ml-auto"></div>
    </div>
</nav>




<main role="main" class="container">
    {% block content %}{% endblock %}
</main>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/sound/leaderboard.html
{% extends 'sound/base.html' %}
{% block content %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
    </head>
    <body>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Username</th>
            <th scope="col">Adds</th>
        </tr>
        </thead>
        <tbody>
        {% for i in profile %}
            <tr>
                <th scope="row"><strong>{{ forloop.counter }}</strong></th>
                <th scope="row"><a class="text-muted">{{ i }}</a></th>
                <th><a class="text-muted">{{ i.adds }}</a></th>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </body>
    </html>
{% endblock %}

templates/sound/main.html
{% extends 'sound/base.html' %}
{% block content %}

<div class="row justify-content-center">
    <div class="col-10 article text-align-center justify-content-center">
        <div class="col-10 article text-align-center justify-content-center">
            {% if error_message %}
                <div class="alert alert-warning" role="alert">
                    {{ error_message }}
                </div>
            {% endif %}
        </div>
        <h1 style="font-size: 50px;">All Sounds</h1>
        <form method="post">
            {% csrf_token %}
            <input type="text" name="search" placeholder="Enter Sound" maxlength="20" required="" id="id_search">
        </form>
        <div class="container">
            <div class="row align-items-start">
                {% if not sound %}
                    <h1 align="center" class="center">UH OH Nothing Found!</h1>
                {% endif %}
                {% for i in sound %}
                    <div class="col-sm audio-card" style="padding-top: 10px;width: 200px; max-width: 200px;">
                        <div class="card" onclick="var audio = new Audio('{{ i.sound.url }}'); audio.play()">
                            <img src="{{ i.image.url }}" alt="sound-image" height="200" width="188">
                            <div class="card-body">
                                <h5 class="card-title center" style="font-size: 15px">{{ i.title }}</h5>
                                {% if user.is_authenticated %}
                                    <form method="post">
                                        {% csrf_token %}
                                        <button class="btn btn-dark" id="val" name="val" value="{{ i.pk }}" style="width: 100%">Add</button>
                                    </form>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    {% if forloop.counter|divisibleby:4 %}
                        <div class="w-100"></div>
                    {% endif %}
                    {% if forloop.last %}
                        <div class="col-sm"></div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>
    <div class="center">
                        {% if is_paginated %}
                            <div class="d-flex justify-content-center page-pagination">
                                {% for num in page_obj.paginator.page_range %}
                                    {% if page_obj.number == num %}
                                        <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                                    {% elif num > page_obj.number|add:'-2' and num < page_obj.number|add:'2' %}
                                        <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        {% endif %}
    </div>
{% endblock content %}

templates/sound/postsound.html
{% extends 'sound/base.html' %}
{% block content %}
    {% load crispy_forms_tags %}
    {% load crispy_forms_filters %}
    <div class="row justify-content-center">
        <div class="col-10 article">
            <div class="card">
                <div class="card-body">
                    <form enctype="multipart/form-data" action="" method="post" id="soundpost_form" novalidate>
                        {% csrf_token %}
                        {{ form|crispy }}
                         <button type="submit" class="btn btn-dark">Submit</button>                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/sound/sound_board.html
{% extends 'sound/base.html' %}
{% block content %}

    <div class="row justify-content-center">
    <div class="col-10 article">
        <h1 class="center">{{ user.username }} - Personal soundboard</h1>
        <div class="row align-items-start">
            {% if add_sounds %}
                <h1 style="padding-top: 10px">You Have No Sounds Click <a href="/">Here</a> To Add Some</h1>            {% endif %}
            <div class="container">
                <div class="row align-items-start">
                    {% for i in user_sound %}
                        <div class="col-sm audio-card" style="padding-top: 10px;width: 200px; max-width: 200px;">
                            <div class="card" onclick="var audio = new Audio('{{ i.sounds.sound.url }}'); audio.play()">
                                <img src="{{ i.sounds.image.url }}" alt="sound-image" height="200" width="188">
                                <div class="card-body">
                                    <h5 class="card-title center" style="font-size: 15px">{{ i.sounds.title }}</h5>
                                    {% if user.is_authenticated %}
                                        <form method="post">
                                            {% csrf_token %}
                                            <button style="width: 100%" class="btn btn-dark" id="prim_key" name="prim_key" value="{{ i.pk }}">Remove</button>
                                        </form>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        {% if forloop.counter|divisibleby:4 %}
                            <div class="w-100"></div>
                        {% endif %}
                        {% if forloop.last %}
                            <div class="col-sm"></div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

templates/users/login.html
{% extends 'sound/base.html' %}
{% block content %}
    {% load crispy_forms_tags %}
    {% load crispy_forms_filters %}
        <div class="row justify-content-center">
            <div class="col-10 article" style="padding-top: 10px">
                <div class="card">
                    <div class="card-body">
                        {% if not user.is_authenticated %}
                        <h2>Login</h2>
                            <form method="post">
                                {% csrf_token %}
                                {{ form|crispy }}
                                <button class="btn btn-secondary" type="submit">Login</button>
                                <a href="{% url 'signup' %}">Dont have an account?</a>
                            </form>
                        {% else %}
                            <div class="justify-content-center align-items-center griddle">
                                <h2>You are already logged in</h2>
                                <p class="text-muted small-text"><a href="{% url 'main' %}">Go back to the homepage</a></p>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
{% endblock content %}

templates/users/logout.html
{% extends 'sound/base.html' %}
{% block content %}
    <div class="row justify-content-center">
         <div class="col-10 article" style="padding-top: 10px">            <div class="card">
                <div class="card-body">
                    <div class="justify-content-center align-items-center griddle">
                        <h2>You have been logged out</h2>
                        <p class="text-muted small-text"><a href="{% url 'login' %}">Login again</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/users/profile.html
{% extends 'sound/main.html' %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-10 article" style="padding-top: 10px">            {% if user.is_authenticated %}
            <div class="card">
                <div class="card-body">
                    <h1 class="title">
                        {{ user.username }} - Profile
                    </h1>
                    <strong>Username - </strong>{{ user.username }}<br>
                    <strong>Email - </strong>{{ user.email }}<br>
                    <strong>Date Joined - </strong>{{ user.date_joined|date:'d M Y' }}<br>
                    <strong>Total Adds - </strong> {{ profile.adds }}<br>
                </div>
            </div>
            <h1 class="title">My sounds:</h1>
            <div class="row align-items-start">
                {% for i in post %}
                    <div class="col-sm audio-card" style="padding-top: 10px;width: 200px; max-width: 200px;">
                        <div class="card" onclick="var audio = new Audio('{{ i.sound.url }}'); audio.play()">
                            <img src="{{ i.image.url }}" alt="sound-image" height="200" width="160">
                            <div class="card-body">
                                <h5 class="card-title center" style="font-size: 15px">{{ i.title }}</h5>
                                {% if user.is_authenticated %}
                                    <form method="post">
                                        {% csrf_token %}
                                        <button style="width: 100%" class="btn btn-dark" id="prim_key" name="prim_key" value="{{ i.pk }}">Delete</button>
                                    </form>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    {% if forloop.counter|divisibleby:4 %}
                        <div class="w-100"></div>
                    {% endif %}
                    {% if forloop.last %}
                        <div class="col-sm"></div>
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}
        </div>
    </div>
{% endblock content %}

templates/users/signup.html
{% extends 'sound/base.html' %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
{% block content %}
    <div class="row justify-content-center">
         <div class="col-10 article" style="padding-top: 10px">
             <div class="card">
                <div class="card-body">
                    {% if not user.is_authenticated %}
                        <h2>Sign Up</h2>
                        <form method="post">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <button class="btn btn-secondary" type="submit">Sign Up</button>
                            <a class="btn btn-link" href="{% url 'login' %}">Already have an account?</a>
                        </form>
                    {% else %}
                    <div class="justify-content-center align-items-center griddle">
                        <h2>You are already logged in</h2>
                        <p class="text-muted small-text"><a href="{% url 'main:index' %}">Go back to the homepage</a></p>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}